[build]
  # Directory to change to before starting a build
  base = "."

  # Directory that contains the deploy-ready HTML files and assets
  publish = "dist"

  # Default build command
  command = "npm run build:netlify"

[build.environment]
  # Node.js version (use LTS version for stability)
  NODE_VERSION = "20"

  # NPM version (optional)
  NPM_VERSION = "10"

  # Increase Node.js memory limit for large builds
  NODE_OPTIONS = "--max-old-space-size=4096"

# SPA (Single Page Application) redirect rules
# This ensures that all routes are handled by React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers for better security
[[headers]]
  for = "/*"
  [headers.values]
    # Prevent clickjacking
    X-Frame-Options = "DENY"
    
    # Prevent MIME type sniffing
    X-Content-Type-Options = "nosniff"
    
    # Enable XSS protection
    X-XSS-Protection = "1; mode=block"
    
    # Referrer policy
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Content Security Policy (Firebase + Google OAuth + Map tiles compatible)
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://apis.google.com https://www.gstatic.com https://*.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https: blob:; font-src 'self' data: https://fonts.gstatic.com; connect-src 'self' https://apis.google.com https://*.googleapis.com https://*.firebaseapp.com https://*.firebase.com https://nominatim.openstreetmap.org https://*.tile.openstreetmap.org https://*.tile.openstreetmap.de https://*.basemaps.cartocdn.com https://firestore.googleapis.com https://identitytoolkit.googleapis.com; frame-src 'self' https://accounts.google.com; object-src 'none'; base-uri 'self';"

# Cache static assets for better performance
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Optimize images
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Environment-specific builds
[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"

# Functions (if you need serverless functions later)
[functions]
  directory = "netlify/functions"
