# Cloudflare Pages Configuration for Where The Cat?
name = "wherethecat"
compatibility_date = "2024-01-15"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[build.environment]
NODE_VERSION = "18"

# Environment variables (set these in Cloudflare Pages dashboard)
[env.production.vars]
# VITE_FIREBASE_API_KEY = "your_firebase_api_key"
# VITE_FIREBASE_AUTH_DOMAIN = "your_project.firebaseapp.com"
# VITE_FIREBASE_PROJECT_ID = "your_project_id"
# VITE_FIREBASE_STORAGE_BUCKET = "your_project.appspot.com"
# VITE_FIREBASE_MESSAGING_SENDER_ID = "your_messaging_sender_id"
# VITE_FIREBASE_APP_ID = "your_app_id"
# VITE_FIREBASE_MEASUREMENT_ID = "your_measurement_id"

# Custom headers for better performance and security
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "geolocation=(self), camera=(self), microphone=()"

# Cache static assets
[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Cache service worker
[[headers]]
for = "/sw.js"
[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

# Cache manifest
[[headers]]
for = "/manifest.json"
[headers.values]
Cache-Control = "public, max-age=86400"

# SPA routing - redirect all routes to index.html
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
